### ISSUE TITLE
Crash while playing in sandscape

### ISSUE THREAD

**Issue by augustoroman** [sillypantscoder/pygame_platformer_2#11]
broked
```
pygame 2.1.2 (SDL 2.0.18, Python 3.10.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/Users/aroman/code/pygame_platformer_2/main.py", line 528, in <module>
    t.tick()
  File "/Users/aroman/code/pygame_platformer_2/main.py", line 211, in tick
    explosion(x, y, 2)
  File "/Users/aroman/code/pygame_platformer_2/main.py", line 172, in explosion
    explosion(*l, 2)
  File "/Users/aroman/code/pygame_platformer_2/main.py", line 151, in explosion
    if BLOCKS[WORLD[x][y]]["collision"] == "explode":
KeyError: 'fall'
```

**Comment by sillypantscoder** [comment]
[Worked](https://github.com/sillypantscoder/pygame_platformer_2/commit/0902a5f7b91c04430e44c7ff6ee3750502702582)
