### ISSUE TITLE
Explosions near bottom and top cause the game to crash

### ISSUE THREAD

**Issue by sillypantscoder** [sillypantscoder/pygame_platformer_2#2]
Whenever I explode some TNT near the top and bottom, the game crashes with the following message:
`Traceback (most recent call last):
File "main.py", line 109, in <module>
    explosion(x, y, 3)
  File "main.py", line 75, in explosion
    explosion(*l, rad)
  File "main.py", line 75, in explosion
    explosion(*l, rad)
  File "main.py", line 75, in explosion
    explosion(*l, rad)
  [Previous line repeated 4 more times]
  File "main.py", line 71, in explosion
    if WORLD[x][y] == 2:
IndexError: list index out of range`

**Comment by sillypantscoder** [comment]
[Fixed](https://github.com/sillypantscoder/pygame_platformer_2/commit/518860cee39f9db0e6eabf223a13eb50a94078ea)
